// LuxLiving catalog data — ported from the Claude Design prototype (LuxLiving Site.dc.html)
// Categories, products, brands, craft-tour slides, techniques, testimonials and Instagram posts.
class LuxData {
  // ---------- DATA ----------
  _categories() {
    return [
      { key: 'living', name: 'Living', img: 'assets/shop/set/01.jpg', desc: 'Sofa Sets, Triple, Two & Single Sitters, Recliner Sofas', tabs: ['All', 'Sofa Sets', 'Triple Sitter', 'Two Sitter', 'Single Sitter', 'Recliner Sofas'] },
      { key: 'armchairs', name: 'Armchairs', img: 'assets/shop/single/06.jpg', desc: 'Lounge Chairs, Swivels & Recliners', tabs: ['All', 'Swivel Chairs', 'Recliners', 'Accent Chairs'] },
      { key: 'bedroom', name: 'Bedroom', img: 'assets/shop/bedroom/01.jpg', desc: 'Upholstered Leather Beds & Benches', tabs: ['All'] },
      { key: 'tables', name: 'Tables', img: 'assets/shop/tables/02.jpg', desc: 'Marble Coffee & Side Tables', tabs: ['All'] },
      { key: 'dining', name: 'Dining', img: 'assets/shop/dining/16.jpg', desc: 'Marble Dining Tables & Sets', tabs: ['All'] },
      { key: 'lighting', name: 'Lighting', img: 'assets/shop/lighting/01.jpg', desc: 'Chandeliers & Ceiling Pendants', tabs: ['All', 'Pendants', 'Chandeliers', 'Linear', 'Wall & Floor'] },
      { key: 'art', name: 'Wall Art', img: 'assets/shop/art/02.jpg', desc: 'Framed Paintings & Textured Canvas', tabs: ['All'] },
      { key: 'pairs', name: 'Pair of Chairs', img: 'assets/shop/pair/01.jpg', desc: 'Matched Lounge Chairs, Sold in Pairs', tabs: ['All'] },
      { key: 'tv', name: 'TV Consoles', img: 'assets/shop/console/04.jpg', desc: 'Marble & Sculptural Media Consoles', tabs: ['All'] },
    ];
  }

  _products() {
    const P = 'assets/products/';
    return [
      { id: 'cocoon-bed', name: 'Cocoon Leather Bed', cat: 'bedroom', sub: 'Beds', imgs: ['assets/shop/bedroom/01.jpg', 'assets/shop/bedroom/02.jpg', 'assets/shop/bedroom/03.jpg'], desc: 'A low-slung king bed wrapped in taupe leather with a curved, pillow-soft headboard and integrated footboard bench — photographed here dressed for the season.', feats: ['Taupe full-grain leather', 'Curved upholstered headboard', 'Integrated footboard bench', 'King & queen sizes'] },
      { id: 'sleeping-bed', name: 'The Sleeping Bed', cat: 'bedroom', sub: 'Beds', imgs: ['assets/shop/bedroom/04.jpg', 'assets/shop/bedroom/05.jpg', 'assets/shop/bedroom/06.jpg'], desc: 'From the aprilstory Sleeping Bed series — a clean-lined platform bed with a tan leather bench and floating nightstands.', feats: ['aprilstory Sleeping Bed series', 'Tan leather end bench', 'Floating nightstand option', 'Solid wood platform base'] },
      { id: 'obsidian-bed', name: 'Obsidian Leather Bed', cat: 'bedroom', sub: 'Beds', imgs: ['assets/shop/bedroom/07.jpg', 'assets/shop/bedroom/08.jpg', 'assets/shop/bedroom/09.jpg'], desc: 'A channel-tufted headboard in deep black leather, dressed in slate and grey and set against a painted lily-pond mural. The matching leather end bench anchors the foot of the bed — dramatic, low and enveloping.', feats: ['Channel-tufted black leather headboard', 'Matching leather end bench', 'Low platform silhouette', 'King and queen sizes'] },
      { id: 'alabaster-bed', name: 'Alabaster Leather Bed', cat: 'bedroom', sub: 'Beds', imgs: ['assets/shop/bedroom/10.jpg', 'assets/shop/bedroom/11.jpg', 'assets/shop/bedroom/12.jpg'], desc: 'The softer sister to Obsidian — a plush cream leather headboard with a rounded channel-tufted top, paired with a cream end bench and sage bedding. Quietly luxurious and endlessly calm.', feats: ['Cream channel-tufted leather headboard', 'Matching cream leather bench', 'Warm ivory-toned frame', 'King and queen sizes'] },
      { id: 'dorado-dining', name: 'Dorado Marble Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 6, imgs: ['assets/shop/dining/01.jpg', 'assets/shop/dining/02.jpg', 'assets/shop/dining/03.jpg'], desc: 'A warm golden-marble top on a sculpted wood base, ringed by ribbed leather chairs — sized for six and made for long, lamplit dinners.', feats: ['Golden veined marble top', 'Sculpted solid-wood base', 'Warm ribbed leather chairs', 'Set of 6 dining chairs'] },
      { id: 'terra-dining', name: 'Terra Stone Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 8, imgs: ['assets/shop/dining/07.jpg', 'assets/shop/dining/08.jpg', 'assets/shop/dining/09.jpg'], desc: 'A sculptural stone top on twin plinth bases, framed by soft bouclé chairs — a quietly architectural setting for eight.', feats: ['Natural stone table top', 'Twin sculptural bases', 'Soft bouclé dining chairs', 'Set of 8 dining chairs'] },
      { id: 'noir-dining', name: 'Noir Stone Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 10, imgs: ['assets/shop/dining/04.jpg', 'assets/shop/dining/06.jpg', 'assets/shop/dining/05.jpg'], desc: 'A long, architectural table in dark stone with matching pedestal bases and graphite chairs — a moody centrepiece that seats ten.', feats: ['Dark stone table top', 'Twin pedestal bases', 'Graphite upholstered chairs', 'Set of 10 dining chairs'] },
      { id: 'toscana-dining', name: 'Toscana Marble Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 8, imgs: ['assets/shop/dining/10.jpg', 'assets/shop/dining/11.jpg', 'assets/shop/dining/12.jpg'], desc: 'Bright white-and-gold marble on a rounded pedestal base, warmed by camel-tan chairs — a sunlit table for eight.', feats: ['White & gold marble top', 'Rounded pedestal base', 'Camel-tan upholstered chairs', 'Set of 8 dining chairs'] },
      { id: 'siena-dining', name: 'Siena Marble Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 8, imgs: ['assets/shop/dining/13.jpg', 'assets/shop/dining/14.jpg', 'assets/shop/dining/15.jpg'], desc: 'Richly veined marble paired with terracotta-toned chairs on a gilt base — an earthy, characterful table for eight.', feats: ['Veined marble top', 'Gilded metal base', 'Terracotta-toned chairs', 'Set of 8 dining chairs'] },
      { id: 'bianca-dining', name: 'Bianca Marble Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 8, imgs: ['assets/shop/dining/16.jpg', 'assets/shop/dining/17.jpg', 'assets/shop/dining/18.jpg'], desc: 'Dramatic white-and-gold marble on a sculptural pedestal, with cream chairs that keep the focus on the stone — elegant seating for eight.', feats: ['White & gold veined marble', 'Sculptural pedestal base', 'Cream upholstered chairs', 'Set of 8 dining chairs'] },
      { id: 'esmeralda-dining', name: 'Esmeralda Green Marble Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 8, imgs: ['assets/shop/dining/21.jpg', 'assets/shop/dining/20.jpg', 'assets/shop/dining/19.jpg'], desc: 'A rare emerald-and-gold marble slab on a brushed base, paired with deep-green velvet chairs — a jewel of a table for eight.', feats: ['Emerald & gold marble top', 'Brushed metal base', 'Deep-green velvet chairs', 'Set of 8 dining chairs'] },
      { id: 'perla-dining', name: 'Perla Marble Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 8, imgs: ['assets/shop/dining/22.jpg', 'assets/shop/dining/23.jpg', 'assets/shop/dining/24.jpg'], desc: 'Soft pearl-grey marble on a sculpted gold base, framed by taupe chairs — a calm, luminous setting for eight.', feats: ['Pearl-grey marble top', 'Sculpted gold base', 'Taupe upholstered chairs', 'Set of 8 dining chairs'] },
      { id: 'alba-dining', name: 'Alba Marble Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 8, imgs: ['assets/shop/dining/25.jpg', 'assets/shop/dining/26.jpg', 'assets/shop/dining/27.jpg'], desc: 'Creamy marble on twin curved bases with pale upholstered chairs — a light, airy table that opens the room for eight.', feats: ['Creamy veined marble top', 'Twin curved bases', 'Pale upholstered chairs', 'Set of 8 dining chairs'] },
      { id: 'onda-dining', name: 'Onda Marble Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 8, imgs: ['assets/shop/dining/28.jpg', 'assets/shop/dining/29.jpg', 'assets/shop/dining/30.jpg'], desc: 'White marble riding a sculpted wave base, with soft chairs all around — a fluid, contemporary table for eight.', feats: ['White marble top', 'Sculpted wave base', 'Soft upholstered chairs', 'Set of 8 dining chairs'] },
      { id: 'ellisse-dining', name: 'Ellisse Oval Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 6, imgs: ['assets/shop/dining/31.jpg', 'assets/shop/dining/32.jpg', 'assets/shop/dining/33.jpg'], desc: 'An oval of golden marble on a slim sculpted base — a softer silhouette that gathers six with room to move.', feats: ['Oval golden marble top', 'Slim sculpted base', 'Rounded upholstered chairs', 'Set of 6 dining chairs'] },
      { id: 'savona-dining', name: 'Savona Marble Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 8, imgs: ['assets/shop/dining/34.jpg', 'assets/shop/dining/35.jpg', 'assets/shop/dining/36.jpg'], desc: 'Pale travertine-look marble on a woven sculptural base, with a warm mix of chairs — a textural table for eight.', feats: ['Travertine-look marble top', 'Woven sculptural base', 'Warm mixed dining chairs', 'Set of 8 dining chairs'] },
      { id: 'onyx-dining', name: 'Onyx Gold-Vein Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 6, imgs: ['assets/shop/dining/37.jpg', 'assets/shop/dining/38.jpg', 'assets/shop/dining/39.jpg'], desc: 'Black marble threaded with gold on a sharp dark base, framed by cream-and-charcoal chairs — graphic, glamorous seating for six.', feats: ['Black gold-veined marble', 'Angular dark base', 'Cream & charcoal chairs', 'Set of 6 dining chairs'] },
      { id: 'milano-dining', name: 'Milano Marble Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 6, imgs: ['assets/shop/dining/40.jpg', 'assets/shop/dining/41.jpg', 'assets/shop/dining/42.jpg'], desc: 'Grey-veined marble on a bold V-shaped base, paired with tailored taupe chairs — a sharp, modern table for six.', feats: ['Grey-veined marble top', 'Sculpted V-shaped base', 'Tailored taupe chairs', 'Set of 6 dining chairs'] },
      { id: 'verona-dining', name: 'Verona Marble Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 6, imgs: ['assets/shop/dining/43.jpg', 'assets/shop/dining/44.jpg', 'assets/shop/dining/45.jpg'], desc: 'Golden marble on a faceted wood base with softly rounded chairs — a warm, welcoming table for six.', feats: ['Golden veined marble top', 'Faceted wood base', 'Rounded upholstered chairs', 'Set of 6 dining chairs'] },
      { id: 'cognac-dining', name: 'Cognac Leather Dining Set', cat: 'dining', sub: 'Dining Sets', seats: 6, imgs: ['assets/shop/dining/46.jpg', 'assets/shop/dining/47.jpg', 'assets/shop/dining/48.jpg'], desc: 'Golden marble paired with rounded cognac-leather armchairs on a drum base — the warmest table on our floor, built for six to linger.', feats: ['Golden marble table top', 'Sculpted drum base', 'Cognac leather armchairs', 'Set of 6 dining chairs'] },
      { id: 'aura-disc', name: 'Aura Wood Disc Pendant', cat: 'lighting', sub: 'Pendants', imgs: ['assets/shop/lighting/01.jpg', 'assets/shop/lighting/02.jpg'], desc: 'A wide wood-veneer disc floats above a polished chrome diffuser, casting a soft up-and-down glow. Shown as a graduated trio over a console or island.', feats: ['Wood-veneer disc shade', 'Polished chrome diffuser', 'Warm dimmable LED', 'Single, pair or trio'] },
      { id: 'cascade-chandelier', name: 'Cascade Icicle Chandelier', cat: 'lighting', sub: 'Chandeliers', imgs: ['assets/shop/lighting/03.jpg', 'assets/shop/lighting/04.jpg'], desc: 'A cluster of slender crystal-and-brass bars dropping at staggered heights — a shower of light for stairwells and double-height voids.', feats: ['Staggered crystal bars', 'Brushed-brass fittings', 'Adjustable drop lengths', 'Statement stairwell piece'] },
      { id: 'ribbon-linear', name: 'Ribbon LED Pendant', cat: 'lighting', sub: 'Linear', imgs: ['assets/shop/lighting/05.jpg', 'assets/shop/lighting/06.jpg'], desc: 'A single continuous ribbon of brushed gold bent into a soft wave, glowing along its full length. Sculpture and light in one line.', feats: ['Continuous LED ribbon', 'Brushed-gold finish', 'Freeform wave form', 'Linear over-table light'] },
      { id: 'drape-chandelier', name: 'Cascade Mesh Chandelier', cat: 'lighting', sub: 'Chandeliers', imgs: ['assets/shop/lighting/07.jpg', 'assets/shop/lighting/08.jpg'], desc: 'A flowing sheet of golden chain-mesh caught mid-drape and lit from within — a soft, molten form that reads as art overhead.', feats: ['Golden chain-mesh drape', 'Internal warm LED', 'Sculptural flowing form', 'Made-to-order sizing'] },
      { id: 'lumiere-linear', name: 'Lumière Crystal Linear', cat: 'lighting', sub: 'Linear', imgs: ['assets/shop/lighting/09.jpg', 'assets/shop/lighting/10.jpg'], desc: 'An elongated ring of faceted crystal beads on a slim frame, throwing a fractured sparkle across the dining table below.', feats: ['Faceted crystal beads', 'Slim elongated frame', 'Brilliant dimmable LED', 'Ideal over long tables'] },
      { id: 'pearl-ring', name: 'Pearl Ring Chandelier', cat: 'lighting', sub: 'Chandeliers', imgs: ['assets/shop/lighting/11.jpg', 'assets/shop/lighting/12.jpg'], desc: 'Hand-strung stone-white spheres form a floating oval halo — a calm, contemporary take on the ring chandelier.', feats: ['Stone-white sphere beads', 'Floating oval halo', 'Warm concealed LED', 'Single or double ring'] },
      { id: 'sketch-linear', name: 'Sketch Gold Linear', cat: 'lighting', sub: 'Linear', imgs: ['assets/shop/lighting/13.jpg', 'assets/shop/lighting/14.jpg'], desc: 'A thin gold line drawn into a loose scribble of light — playful, minimal and surprisingly bright over a table or counter.', feats: ['Thin gold LED line', 'Freehand scribble form', 'Fully dimmable', 'Over-table or counter'] },
      { id: 'orbit-cluster', name: 'Orbit Orb Cluster', cat: 'lighting', sub: 'Pendants', imgs: ['assets/shop/lighting/15.jpg', 'assets/shop/lighting/16.jpg'], desc: 'A cluster of marbled-glass orbs suspended at different heights, each a soft globe of light. A group of three, made to your ceiling.', feats: ['Marbled-glass orbs', 'Staggered cluster hang', 'Warm dimmable LED', 'Trio, custom drops'] },
      { id: 'lumen-dome', name: 'Lumen Smoked-Glass Dome', cat: 'lighting', sub: 'Pendants', imgs: ['assets/shop/lighting/17.jpg', 'assets/shop/lighting/18.jpg'], desc: 'A flat smoked-glass dome with a warm amber glow — a quietly retro pendant that groups beautifully in twos and threes.', feats: ['Smoked amber glass', 'Low-profile dome shade', 'Warm dimmable LED', 'Single, pair or trio'] },
      { id: 'halo-rings', name: 'Halo Interlocking Rings', cat: 'lighting', sub: 'Linear', imgs: ['assets/shop/lighting/19.jpg', 'assets/shop/lighting/20.jpg'], desc: 'Three gold rings caught mid-tumble, each edged in light — a kinetic, jewellery-like fixture for above the dining table.', feats: ['Interlocking lit rings', 'Brushed-gold finish', 'Adjustable ring angles', 'Linear over-table drop'] },
      { id: 'harvest-canvas', name: 'Golden Harvest Canvas', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop/art/01.jpg'], desc: 'A tall, palette-knife canvas of wheat catching low golden light — heavy texture and warm ochres that hold a room together.', feats: ['Hand-textured palette knife', 'Warm ochre & gold tones', 'Slim black gallery frame', 'Portrait, statement scale'] },
      { id: 'botanica-triptych', name: 'Botanica Triptych', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop/art/02.jpg'], desc: 'Three framed botanical studies — wheat, feather and leaf — in soft neutrals and gold, hung together as one quiet composition.', feats: ['Set of three framed prints', 'Soft neutral & gold palette', 'Natural botanical studies', 'Cream mount, wood frame'] },
      { id: 'aurelia-canvas', name: 'Aurelia Textured Canvas', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop/art/03.jpg'], desc: 'An abstract burst of pale gold worked in thick impasto — a square canvas that reads as light itself from across the room.', feats: ['Thick impasto texture', 'Pale gold on ivory', 'Square gallery format', 'Frameless clean edge'] },
      { id: 'harbour-canvas', name: 'Harbour Lights Canvas', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop/art/04.jpg'], desc: 'An impressionist harbour at dusk — violets, golds and lamplit water in loose, confident strokes. The one piece with colour to spare.', feats: ['Impressionist harbour scene', 'Violet & gold palette', 'Loose expressive strokes', 'Framed, portrait format'] },
      { id: 'ginkgo-canvas', name: 'Amber Ginkgo Canvas', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop/art/05.jpg'], desc: 'A wide, panoramic palette-knife painting — a single tree heavy with amber and gold leaves, built up in thick impasto against a moody grey-blue ground. A statement piece for above a console or bed.', feats: ['Palette-knife impasto texture', 'Panoramic landscape format', 'Amber & gold on slate ground', 'Slim black gallery frame'] },
      { id: 'horizon-mosaic', name: 'Horizon Mosaic Relief', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop/art/06.jpg'], desc: 'A dimensional relief of hundreds of hand-set tiles, graduating from pale sun through amber to deep sea-blue — a sunset over water, rendered in shadow and texture. Framed as a floating shadow-box.', feats: ['Hand-set dimensional tiles', 'Sunset-to-sea gradient', 'Floating shadow-box frame', 'Catches & throws light'] },
      { id: 'console-marble', name: 'Sculptural Marble Console', cat: 'tv', sub: 'Consoles', imgs: ['assets/shop/console/01.jpg', 'assets/shop/console/02.jpg', 'assets/shop/console/03.jpg'], desc: 'A long marble-topped console on a faceted black base — media storage that reads as sculpture.', feats: ['Faceted sculptural base', 'Veined marble top', 'Concealed media storage', 'Low-slung profile'] },
      { id: 'floating-console', name: 'Rattan & Marble Console', cat: 'tv', sub: 'Consoles', imgs: ['assets/shop/console/06.jpg', 'assets/shop/console/04.jpg', 'assets/shop/console/05.jpg'], desc: 'A slab of white marble floating over woven cabinet fronts, lifted on slim gold legs — six feet of quiet drama for the media wall.', feats: ['White marble slab top', 'Woven textured doors', 'Slim gold-tone legs', 'Cable-friendly storage'] },
      { id: 'midnight-bed', name: 'Midnight Leather Bed', cat: 'bedroom', sub: 'Beds', imgs: ['assets/shop/bedroom/13.jpg', 'assets/shop/bedroom/14.jpg', 'assets/shop/bedroom/15.jpg'], desc: 'A deep navy leather platform bed with a matching end bench — dressed for dusk.', feats: ['Navy leather upholstery', 'Matching end bench', 'Low platform frame', 'King & queen sizes'] },
      { id: 'azure-relief', name: 'Azure Radiance Relief', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop/art/07.jpg'], desc: 'A turquoise-and-gold radial burst in carved relief.', feats: ['Carved radial relief', 'Turquoise & gold palette', 'Square format', 'Catches ambient light'] },
      { id: 'tectonic-panel', name: 'Tectonic Panel', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop/art/08.jpg'], desc: 'Layered geometry in sand, black and rust over woven texture.', feats: ['Layered geometric forms', 'Sand, black & rust', 'Woven texture ground', 'Portrait format'] },
      { id: 'ember-canvas', name: 'Ember Field Canvas', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop/art/09.jpg'], desc: 'An amber landscape burning quietly in thick texture.', feats: ['Thick impasto texture', 'Amber & ember palette', 'Wide landscape format', 'Black gallery frame'] },
      { id: 'veiled-diptych', name: 'Veiled Gaze Diptych', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop/art/10.jpg'], desc: 'A two-frame study of a face behind perforated light.', feats: ['Two-frame diptych', 'Gold slim frames', 'Contrast light study', 'Hang together or apart'] },
      { id: 'tide-relief', name: 'Monochrome Tide Relief', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop/art/11.jpg'], desc: 'A black-and-white tide rendered in raked, dimensional texture.', feats: ['Raked dimensional texture', 'Black & white palette', 'Wide landscape format', 'Quiet graphic presence'] },
      { id: 'halo-wall-light', name: 'Halo Discs Wall Light', cat: 'lighting', sub: 'Wall & Floor', imgs: ['assets/shop/lighting/21.jpg'], desc: 'Marble-print discs glowing from behind — a constellation for the console wall.', feats: ['Backlit marble discs', 'Warm halo glow', 'Cluster arrangement', 'Hardwired install'] },
      { id: 'lanterna-floor-lamp', name: 'Lanterna Floor Lamp', cat: 'lighting', sub: 'Wall & Floor', imgs: ['assets/shop/lighting/22.jpg'], desc: 'A woven double-lantern column that throws patterned light across the room.', feats: ['Woven double lantern', 'Patterned light play', 'Floor-standing column', 'Warm brass details'] },
      { id: 'barley-two', name: 'Barley Chenille Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop2/living/01a.jpg', 'assets/shop2/living/01b.jpg'], desc: 'Two seats wrapped in richly textured oat chenille, with low stacked bolster arms and a deep, relaxed sit — softness you can read from across the room.', feats: ['Textured oat chenille', 'Stacked bolster arms', 'Deep relaxed seats', 'Low modern profile'] },
      { id: 'sedona-two', name: 'Sedona Leather Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop2/living/02a.jpg', 'assets/shop2/living/02b.jpg'], desc: 'Caramel leather with plump pillow-top arms and wide cushions — a two-seater that sits like a much bigger sofa.', feats: ['Caramel Italian leather', 'Pillow-top arms', 'Wide supportive cushions', 'Solid hardwood frame'] },
      { id: 'vienna-two', name: 'Vienna Leather Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop2/living/04a.jpg', 'assets/shop2/living/04b.jpg'], desc: 'High comfort backs and lifted headrests in warm cognac leather, floating on slim black tapered legs.', feats: ['Cognac leather', 'High supportive backs', 'Slim black tapered legs', 'Tailored stitching'] },
      { id: 'pebble-curved-two', name: 'Pebble Curved Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop2/living/05a.jpg', 'assets/shop2/living/05b.jpg'], desc: 'A gently curved shell in speckled bouclé that wraps its two seats like a pebble worn smooth — organic, sculptural, and impossibly soft.', feats: ['Curved wraparound shell', 'Speckled bouclé weave', 'Organic sculptural form', 'Feather-soft seats'] },
      { id: 'modena-recliner-two', name: 'Modena Reclining Two-Seater', cat: 'living', sub: 'Recliner Sofas', imgs: ['assets/shop2/living/06a.jpg', 'assets/shop2/living/06b.jpg', 'assets/shop2/living/06c.jpg'], desc: 'A mocha leather two-seater recliner — both seats recline independently, with adjustable headrests and chunky padded arms.', feats: ['Two reclining seats', 'Adjustable headrests', 'Mocha full-grain leather', 'Chunky padded arms'] },
      { id: 'aria-recliner-pair', name: 'Aria Swivel Recliner Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop2/pairs/01a.jpg', 'assets/shop2/pairs/01b.jpg', 'assets/shop/arm/01.jpg', 'assets/shop/arm/02.jpg'], desc: 'A matched pair of high-back swivel recliners in tan leather with channel-stitched backs — sold as a set of two, made for facing conversations.', feats: ['Sold as a set of two', 'High channel-stitched backs', 'Swivel and recline', 'Tan top-grain leather'] },
      { id: 'sirocco-lounge-pair', name: 'Sirocco Chrome Lounge Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop2/pairs/02a.jpg', 'assets/shop2/pairs/02b.jpg', 'assets/shop2/pairs/02c.jpg', 'assets/shop/arm/04.jpg'], desc: 'Two rounded cognac leather lounges suspended in polished chrome frames with padded arm rests — light on their feet, rich to the touch.', feats: ['Sold as a set of two', 'Polished chrome frames', 'Cognac leather shells', 'Padded floating armrests'] },
      { id: 'cascade-swivel', name: 'Cascade Swivel Armchair', cat: 'armchairs', sub: 'Swivel Chairs', imgs: ['assets/shop2/arm/01a.jpg', 'assets/shop2/arm/01b.jpg'], desc: 'Channel-stitched cognac leather cascading over a deep bucket seat, turning on a matte black disc base.', feats: ['Channel-stitched leather', 'Matte black disc base', '360° swivel', 'Deep bucket seat'] },
      { id: 'verve-lounge-pair', name: 'Verve Gold Lounge Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop2/pairs/03a.jpg', 'assets/shop2/pairs/03b.jpg', 'assets/shop2/pairs/03c.jpg'], desc: 'A matched pair of sculpted lounge chairs — geometric jacquard shells, taupe leather seats and sweeping rose-gold arms on sabre legs.', feats: ['Sold as a set of two', 'Geometric jacquard shells', 'Rose-gold sweeping arms', 'Taupe leather seats'] },
      { id: 'saffron-recliner', name: 'Saffron Swivel Recliner', cat: 'armchairs', sub: 'Recliners', imgs: ['assets/shop2/arm/02a.jpg', 'assets/shop2/arm/02b.jpg', 'assets/shop/arm/08.jpg', 'assets/shop/arm/09.jpg'], desc: 'A ray of saffron-yellow leather with power recline, padded headrest and a polished star base — the brightest seat in the house.', feats: ['Saffron-yellow leather', 'Power recline controls', 'Padded headrest', 'Polished star swivel base'] },
      { id: 'tawny-tub-pair', name: 'Tawny Tub Chair Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop2/pairs/04a.jpg', 'assets/shop2/pairs/04b.jpg', 'assets/shop2/pairs/04c.jpg'], desc: 'Two barrel-back tub chairs in tawny leather, curled around deep cushioned seats on slim gunmetal feet — sold as a matched pair.', feats: ['Sold as a set of two', 'Barrel-back silhouette', 'Tawny full-grain leather', 'Slim gunmetal feet'] },
      { id: 'crema-recliner', name: 'Crema Power Recliner', cat: 'armchairs', sub: 'Recliners', imgs: ['assets/shop2/arm/03a.jpg', 'assets/shop2/arm/03b.jpg'], desc: 'A tall cream leather recliner with layered back cushions, one-touch power recline and a brushed steel swivel base.', feats: ['Cream full-grain leather', 'One-touch power recline', 'Layered back cushions', 'Brushed steel swivel base'] },
      { id: 'garnet-accent', name: 'Garnet Chenille Accent Chair', cat: 'armchairs', sub: 'Accent Chairs', imgs: ['assets/shop2/arm/04a.jpg'], desc: 'A rounded tub chair in flecked garnet chenille over a dark leather base — a warm, textural jewel for a reading corner.', feats: ['Flecked garnet chenille', 'Dark leather base band', 'Rounded barrel silhouette', 'Compact accent scale'] },
      { id: 'cirrus-recliner-pair', name: 'Cirrus Cream Recliner Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop2/pairs/05a.jpg', 'assets/shop2/pairs/05b.jpg'], desc: 'Two cloud-soft cream leather loungers with roll-forward seats on hidden swivel bases — sold as a matched pair for easy, facing relaxation.', feats: ['Sold as a set of two', 'Cloud-soft cream leather', 'Roll-forward seat cushions', 'Hidden swivel bases'] },
      { id: 'tallow-lounge-pair', name: 'Tallow Leather Lounge Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop2/pairs/06a.jpg', 'assets/shop2/pairs/06b.jpg'], desc: 'A matched pair of tallow-tan leather lounge chairs with lifted headrests and slim splayed legs — quietly mid-century, built for conversation.', feats: ['Sold as a set of two', 'Tallow-tan leather', 'Lifted headrests', 'Slim splayed legs'] },
      { id: 'crestone-sectional', name: 'Crestone Curved Leather Sectional', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop2/triple/01a.jpg', 'assets/shop2/triple/01b.jpg', 'assets/shop2/triple/01c.jpg'], desc: 'A sweeping cognac leather sectional that curves through the room in one continuous run — low-backed, deep-seated, and made for a crowd.', feats: ['Continuous curved form', 'Cognac leather', 'Seats five or more', 'Low contemporary back'] },
      { id: 'dune-curved-sofa', name: 'Dune Curved Chenille Sofa', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop2/triple/02a.jpg', 'assets/shop2/triple/02b.jpg'], desc: 'A serpentine three-seater in sand chenille with a soft curved back and a companion lounge chair — sculptural and endlessly soft.', feats: ['Curved serpentine form', 'Sand chenille weave', 'Deep feather-soft seats', 'Companion chair available'] },
      { id: 'frame-three', name: 'Frame Leather Three-Seater', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop2/triple/03a.jpg', 'assets/shop2/triple/03b.jpg'], desc: 'Warm tan leather with channel-tufted backs on slim splayed legs — a crisp, gallery-ready three-seater.', feats: ['Warm tan leather', 'Channel-tufted backs', 'Slim splayed legs', 'Three-seat length'] },
      { id: 'savanna-sectional', name: 'Savanna Chenille Sectional', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop2/triple/04a.jpg', 'assets/shop2/triple/04b.jpg'], desc: 'An L-sectional in soft oat patterned chenille with plump bolster arms — a big, welcoming landing spot for the whole family.', feats: ['L-shaped configuration', 'Oat patterned chenille', 'Plump bolster arms', 'Seats five'] },
      { id: 'lido-three', name: 'Lido Leather Three-Seater', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop2/triple/05a.jpg', 'assets/shop2/triple/05b.jpg'], desc: 'Soft sand leather with pillowy stitched backs on slim dark legs — an easy, relaxed three-seater dressed with a throw.', feats: ['Soft sand leather', 'Pillowy stitched backs', 'Slim dark legs', 'Three-seat comfort'] },
      { id: 'olive-grove-sectional-lg', name: 'Olive Grove Leather Sectional', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop2/triple/06a.jpg', 'assets/shop2/triple/06b.jpg', 'assets/shop2/triple/06c.jpg'], desc: 'A long olive-khaki leather sectional with dual chaise ends and lifted headrests — earthy, architectural and built to stretch out on.', feats: ['Olive-khaki leather', 'Dual chaise ends', 'Adjustable headrests', 'Seats six'] },
      { id: 'aurelio-three', name: 'Aurelio Leather Three-Seater', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop2/triple/07a.jpg', 'assets/shop2/triple/07b.jpg', 'assets/shop2/triple/07c.jpg'], desc: 'Golden-caramel leather with channel-stitched cushions on slim tapered legs — a warm, sunlit three-seater with quiet presence.', feats: ['Golden-caramel leather', 'Channel-stitched cushions', 'Slim tapered legs', 'Three-seat length'] },
      { id: 'boulder-grey-set', name: 'Boulder Grey Chenille Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop2/set/01a.jpg', 'assets/shop2/set/01b.jpg', 'assets/shop2/set/01c.jpg'], desc: 'Deep biscuit-tufted chenille in stone grey with a solid-wood base rail — a complete low-slung living set built like a cloud on a plinth.', feats: ['Biscuit-tufted chenille', 'Stone-grey tone', 'Solid-wood base rail', 'Complete living set'] },
      { id: 'boulder-sand-set', name: 'Boulder Sand Chenille Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop2/set/02a.jpg', 'assets/shop2/set/02b.jpg', 'assets/shop2/set/02c.jpg'], desc: 'The Boulder in warm sand chenille — the same plump tufted seating and wood base, dressed for a lighter room.', feats: ['Biscuit-tufted chenille', 'Warm sand tone', 'Solid-wood base rail', 'Complete living set'] },
      { id: 'sienna-leather-set', name: 'Sienna Leather Sofa Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop2/set/03a.jpg', 'assets/shop3/set/Sienna1.jpg', 'assets/shop3/set/Sienna2.jpg'], desc: 'A warm tan leather three-plus-one arrangement with lifted headrests and slim metal legs — a complete, gallery-ready living set.', feats: ['Warm tan leather', 'Adjustable headrests', 'Sofa + armchairs', 'Slim metal legs'] },
      { id: 'ivory-leather-set', name: 'Ivory Leather Sofa Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop2/set/04a.jpg'], desc: 'Soft ivory leather sofas paired with cognac swivel tubs around a walnut-and-marble table — a bright, layered living arrangement.', feats: ['Ivory full-grain leather', 'Cognac accent chairs', 'Sofa + tub chairs', 'Warm neutral palette'] },
      { id: 'moss-sectional-set', name: 'Moss Leather Sectional Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop2/set/05a.jpg'], desc: 'An olive-green leather sectional flanked by tan swivel recliners — an earthy, grounded set for a relaxed family room.', feats: ['Olive-green leather', 'Tan swivel recliners', 'Sectional + chairs', 'Earthy palette'] },
      { id: 'harmony-recliner-set', name: 'Harmony Recliner Sofa Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop2/set/06a.jpg'], desc: 'A warm tan leather recliner sofa with matching cream power-recliner chairs — a full home-theatre set built for long evenings.', feats: ['Tan & cream leather', 'Power recline throughout', 'Sofa + recliner chairs', 'Padded headrests'] },
      { id: 'sahara-leather-set', name: 'Sahara Leather Sofa Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop2/set/07a.jpg', 'assets/shop2/set/07b.jpg', 'assets/shop2/set/07c.jpg'], desc: 'Camel leather three-, two- and single-seaters on slim dark legs, arranged around a sculptural coffee table — a warm, complete living suite.', feats: ['Camel full-grain leather', '3 + 2 + 1 arrangement', 'Slim dark legs', 'Complete living set'] },
      { id: 'caramel-lounge-set', name: 'Caramel Lounge Sofa Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop2/set/08a.jpg', 'assets/shop/set2/10.jpg'], desc: 'Caramel leather sofas with rounded pillow arms and swivel accent chairs, gathered around a marble table — a soft, sociable living set.', feats: ['Caramel leather', 'Rounded pillow arms', 'Sofa + swivel chairs', 'Marble centre table'] },
      { id: 'blossom-boucle-set', name: 'Blossom Bouclé Sofa Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop2/set/09a.jpg'], desc: 'A cream bouclé curved sofa paired with flecked mauve lounge chairs — a soft, romantic set with rounded, sculptural silhouettes.', feats: ['Cream bouclé sofa', 'Flecked mauve chairs', 'Rounded silhouettes', 'Soft romantic palette'] },
      { id: 'meridian-split-table', name: 'Meridian Split Marble Table', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop2/tables/01a.jpg', 'assets/shop2/tables/01b.jpg'], desc: 'A round black-marble top split and offset over a dark walnut shelf — a graphic, gold-veined centrepiece with room for books below.', feats: ['Split black-marble top', 'Gold-veined figuring', 'Walnut lower shelf', 'Round silhouette'] },
      { id: 'halo-nesting-table', name: 'Halo Nesting Coffee Tables', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop2/tables/02a.jpg', 'assets/shop2/tables/02b.jpg'], desc: 'A smoked-glass round and a white-marble round nested over a walnut base with a tan leather drum — mixed materials, layered heights.', feats: ['Smoked glass + marble', 'Walnut base disc', 'Leather drum canister', 'Nesting pair'] },
      { id: 'eclipse-glass-table', name: 'Eclipse Glass & Marble Table', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop2/tables/03a.jpg', 'assets/shop2/tables/03b.jpg'], desc: 'A tinted-glass round sliding over a walnut disc beside a white-marble round on a slim base — an overlapping, eclipse-like pairing.', feats: ['Tinted glass top', 'White marble companion', 'Walnut base disc', 'Overlapping rounds'] },
      { id: 'orzo-nesting-table', name: 'Orzo Nesting Stone Tables', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop2/tables/04a.jpg', 'assets/shop2/tables/04b.jpg'], desc: 'Two soft-cornered tops — creamy stone and glossy espresso — on sculpted dark bases that nest and slide apart as you please.', feats: ['Cream stone + espresso tops', 'Soft-cornered squares', 'Sculpted dark bases', 'Nesting pair'] },
      { id: 'lotus-marble-table', name: 'Lotus Marble Nesting Table', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop2/tables/05a.jpg', 'assets/shop2/tables/05b.jpg'], desc: 'Two pebble-form white-marble tops on dark sculptural bases — nesting rounds with soft, organic edges and grey veining.', feats: ['Pebble-form marble tops', 'Grey veined figuring', 'Dark sculptural bases', 'Nesting pair'] },
      { id: 'kidney-walnut-table', name: 'Kidney Walnut & Marble Table', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop2/tables/06a.jpg', 'assets/shop2/tables/06b.jpg'], desc: 'A retro kidney-shaped top in walnut inset with a white-marble oval, floating on tapered wood legs — mid-century warmth in one sweep.', feats: ['Kidney-shaped top', 'Walnut + marble inlay', 'Tapered wood legs', 'Mid-century form'] },
      { id: 'tulipa-noir-pair-2', name: 'Tulipa Black-Marble Pair', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop2/tables/07a.jpg', 'assets/shop2/tables/07b.jpg'], desc: 'Gold-veined black-marble tops on sculpted tulip pedestals — a glossy, glamorous pair in two heights.', feats: ['Gold-veined black marble', 'Sculpted tulip pedestals', 'High-gloss finish', 'Nesting pair'] },
      { id: 'tellus-tray-table', name: 'Tellus Tray Coffee Table', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop2/tables/08a.jpg', 'assets/shop2/tables/08b.jpg'], desc: 'A taupe leather-wrapped tray base cradling a dark-oak liner and a cream onyx-marble top — a soft, layered plinth of a table.', feats: ['Leather-wrapped tray base', 'Dark-oak liner', 'Cream onyx-marble top', 'Low plinth form'] },
      { id: 'ombra-nesting-table', name: 'Ombra Stone-Glass Nesting Pair', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop2/tables/09a.jpg', 'assets/shop2/tables/09b.jpg'], desc: 'Two pebble-form tops in smoky stone-print glass on glossy black drum bases — a sculptural nesting pair that reads soft and monolithic at once.', feats: ['Stone-print smoked glass', 'Glossy black drum bases', 'Pebble-form tops', 'Nesting pair'] },
      { id: 'monolith-marble-table', name: 'Monolith Marble Plinth Table', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop2/tables/10a.jpg', 'assets/shop2/tables/10b.jpg'], desc: 'A square white-marble top floating on a stepped wood-and-taupe plinth, cantilevered over a brass-footed dark drum — quiet mass with a sharp modern edge.', feats: ['Square marble top', 'Stepped wood plinth', 'Brass-footed drum', 'Cantilevered profile'] },
      { id: 'luna-marble-nest', name: 'Luna Marble Nesting Tables', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop2/tables/11a.jpg', 'assets/shop2/tables/11b.jpg'], desc: 'An oval and a soft-square white-marble top on sculpted dark U-bases — a nesting pair that slides together into one continuous stone surface.', feats: ['White veined marble', 'Sculpted dark U-bases', 'Oval + soft-square tops', 'Nesting pair'] },
      { id: 'cognac-x-swivel', name: 'Cognac X-Stitch Swivel Chair', cat: 'armchairs', sub: 'Swivel Chairs', imgs: ['assets/shop3/arm/01a.jpg', 'assets/shop3/arm/01b.jpg', 'assets/shop3/arm/01c.jpg', 'assets/shop/single/03.jpg'], desc: 'A rounded cognac leather lounge chair with a single X-stitched seat button, curved to cradle you and spun on a hidden swivel base.', feats: ['Cognac full-grain leather', 'Single X-stitch detail', 'Rounded barrel form', 'Hidden swivel base'] },
      { id: 'olive-tufted-recliner', name: 'Olive Tufted Power Recliner', cat: 'armchairs', sub: 'Recliners', imgs: ['assets/shop3/arm/02a.jpg', 'assets/shop3/arm/02b.jpg'], desc: 'A deep olive leather recliner with a channel-tufted back and one-touch power recline — earthy, enveloping and built for the long evening.', feats: ['Olive-green leather', 'Channel-tufted back', 'One-touch power recline', 'Swivel base'] },
      { id: 'cream-tufted-wingback', name: 'Cream Tufted Wingback', cat: 'armchairs', sub: 'Accent Chairs', imgs: ['assets/shop3/arm/03a.jpg', 'assets/shop3/arm/03b.jpg'], desc: 'A tall grid-tufted wingback in cream leather on slim black splayed legs — a quietly regal reading chair.', feats: ['Cream grid-tufted leather', 'High wingback silhouette', 'Slim splayed legs', 'Firm supportive seat'] },
      { id: 'walnut-recliner-ottoman', name: 'Walnut Leather Recliner & Ottoman', cat: 'armchairs', sub: 'Recliners', imgs: ['assets/shop3/arm/04a.jpg', 'assets/shop3/arm/04b.jpg'], desc: 'A mid-century brown leather lounge chair with its matching ottoman on tapered black legs — lean, warm and endlessly loungeable.', feats: ['Warm brown leather', 'Matching ottoman included', 'Tapered black legs', 'Mid-century profile'] },
      { id: 'serenity-massage-recliner', name: 'Serenity Massage Recliner', cat: 'armchairs', sub: 'Recliners', imgs: ['assets/shop3/arm/05a.jpg', 'assets/shop3/arm/05b.jpg'], desc: 'A full-body massage recliner in beige and gold with zero-gravity recline, a tablet control and a wrap-around calf cradle.', feats: ['Full-body massage programs', 'Zero-gravity recline', 'Tablet controller', 'Beige & gold finish'] },
      { id: 'ochre-tub-chair', name: 'Ochre Leather Tub Chair', cat: 'armchairs', sub: 'Accent Chairs', imgs: ['assets/shop3/arm/06a.jpg'], desc: 'A warm ochre leather tub chair with a lifted headrest and slim black legs — a single hit of colour for a quiet corner.', feats: ['Ochre-mustard leather', 'Lifted headrest', 'Slim black legs', 'Compact tub form'] },
      { id: 'cognac-tub-pair-2', name: 'Cognac Rounded Tub Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop3/pair/01a.jpg', 'assets/shop3/pair/01b.jpg', 'assets/shop3/pair/01c.jpg'], desc: 'Two plump cognac leather tub chairs with a single seat button and rounded wraparound arms — sold as a matched pair for facing conversation.', feats: ['Sold as a set of two', 'Cognac full-grain leather', 'Rounded wraparound arms', 'Single-button seat'] },
      { id: 'ivory-cloud-pair', name: 'Ivory Cloud Swivel Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop3/pair/02a.jpg', 'assets/shop3/pair/02b.jpg'], desc: 'A matched pair of ivory leather loungers with pillowy layered cushions cradled in a black shell on a star swivel base.', feats: ['Sold as a set of two', 'Pillowy ivory cushions', 'Black shell + star base', '360° swivel'] },
      { id: 'ivory-noir-shell-pair', name: 'Ivory & Noir Shell Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop3/pair/03a.jpg', 'assets/shop3/pair/03b.jpg', 'assets/shop3/pair/03c.jpg'], desc: 'Deep ivory cushions set into sculptural black leather shells on splayed metal legs — a graphic, low-slung lounge pair.', feats: ['Sold as a set of two', 'Ivory on black shell', 'Splayed metal legs', 'Low lounge angle'] },
      { id: 'cognac-curved-tub-pair', name: 'Cognac Curved Tub Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop3/pair/04a.jpg', 'assets/shop3/pair/04b.jpg'], desc: 'Two richly curved cognac leather tubs with a soft channel seat — compact, warm and endlessly inviting as a pair.', feats: ['Sold as a set of two', 'Cognac leather', 'Deep curved tub', 'Channel-stitched seat'] },
      { id: 'egg-swivel-pair', name: 'Ivory Egg Swivel Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop3/pair/05a.jpg', 'assets/shop3/pair/05b.jpg'], desc: 'A pair of egg-form lounge chairs — ivory cushions in a black leather cradle on a black star base that turns to face the room.', feats: ['Sold as a set of two', 'Egg-form silhouette', 'Ivory on black leather', 'Star swivel base'] },
      { id: 'rust-jleg-pair', name: 'Rust Chenille Lounge Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop3/pair/06a.jpg', 'assets/shop3/pair/06b.jpg'], desc: 'Two mid-century lounge chairs in rust-striped chenille on sculptural black J-shaped legs — a warm, retro-modern matched pair.', feats: ['Sold as a set of two', 'Rust-striped chenille', 'Sculptural J-legs', 'Padded open arms'] },
      { id: 'sienna-tub-set', name: 'Sienna Tub-Chair Sofa Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop3/set/01a.jpg', 'assets/shop3/set/01b.jpg', 'assets/shop3/set/01c.jpg'], desc: 'Warm caramel leather sofas paired with rounded ivory tub chairs around a black-and-marble table — a complete, sociable living suite.', feats: ['Caramel leather sofas', 'Ivory tub accent chairs', 'Complete living set', 'Warm neutral palette'] },
      { id: 'atlas-u-sectional-set', name: 'Atlas U-Sectional Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop3/set/02a.jpg', 'assets/shop3/set/02b.jpg', 'assets/shop3/set/02c.jpg'], desc: 'A tan leather U-sectional with lifted headrests, joined by rounded cognac swivel tubs around an oval marble table.', feats: ['Tan U-sectional', 'Adjustable headrests', 'Cognac swivel tubs', 'Oval marble table'] },
      { id: 'savoy-grande-set', name: 'Savoy Grande Leather Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop3/set/03a.jpg'], desc: 'A full caramel leather suite — three-, two- and single-seaters arranged around a round marble table for a whole-room gathering.', feats: ['Caramel leather', '3 + 2 + 1 arrangement', 'Round marble table', 'Complete living set'] },
      { id: 'noir-egg-set', name: 'Noir Leather Lounge Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop3/set/04a.jpg', 'assets/shop3/set/04b.jpg', 'assets/shop3/set/04c.jpg'], desc: 'Midnight-black leather sofas gathered with ivory-cushioned black egg swivel chairs beneath a ring chandelier — dramatic and complete.', feats: ['Black leather sofas', 'Ivory egg swivel chairs', 'Complete lounge floor', 'High-contrast palette'] },
      { id: 'perla-u-set', name: 'Perla U-Sectional Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop3/set/05a.jpg', 'assets/shop3/set/05b.jpg'], desc: 'A soft taupe leather U-sectional with lifted headrests and rounded cognac tub chairs around a travertine table — a calm, generous set.', feats: ['Taupe U-sectional', 'Adjustable headrests', 'Cognac tub chairs', 'Travertine table'] },
      { id: 'noir-rust-set', name: 'Noir & Rust Lounge Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop3/set/06a.jpg', 'assets/shop3/set/06b.jpg'], desc: 'A black leather sofa suite warmed by rust-striped J-leg accent chairs and a split black-and-travertine table — moody and characterful.', feats: ['Black leather sofas', 'Rust chenille accent chairs', 'Split-top coffee table', 'Warm-cool contrast'] },
      { id: 'aurelia-recliner-set', name: 'Aurelia Recliner Sofa Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop3/set/07a.jpg', 'assets/shop3/set/07b.jpg', 'assets/shop3/set/07c.jpg'], desc: 'A cream leather recliner sofa paired with rounded cognac tub chairs around a kidney marble table — soft, warm and made for lingering.', feats: ['Cream recliner sofa', 'Cognac tub chairs', 'Kidney marble table', 'Power recline'] },
      { id: 'moss-recliner-set', name: 'Moss Sectional Recliner Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop3/set/08a.jpg', 'assets/shop3/set/08b.jpg', 'assets/shop3/set/08c.jpg'], desc: 'An olive-green leather sectional flanked by cream power-recliner lounge chairs — an earthy, fully-loaded home-theatre set.', feats: ['Olive-green sectional', 'Cream power recliners', 'Complete theatre set', 'Earthy palette'] },
      { id: 'cambridge-recliner-set', name: 'Cambridge Recliner Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop3/set/09a.jpg', 'assets/shop3/set/09b.jpg'], desc: 'A cognac leather sofa paired with two cream leather power-recliner lounge chairs — a warm two-tone set built around comfort.', feats: ['Cognac leather sofa', 'Cream power recliners', 'Two-tone palette', 'Padded headrests'] },
      { id: 'olive-grande-set', name: 'Olive Grande Leather Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop3/set/10a.jpg', 'assets/shop3/set/10b.jpg', 'assets/shop3/set/10c.jpg'], desc: 'A large olive-brown leather suite — twin curved sofas with cream power-recliner chairs beneath a sculptural gold pendant.', feats: ['Olive-brown leather', 'Twin curved sofas', 'Cream recliner chairs', 'Showroom-scale set'] },
      { id: 'aprilstory-chaise', name: 'Aprilstory Leather Chaise Sofa', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop3/tri/01a.jpg', 'assets/shop3/tri/01b.jpg'], desc: 'A warm brown leather three-seater with an open chaise return and a single accent bolster — clean, low and easy to sink into.', feats: ['Warm brown leather', 'Open chaise return', 'Low contemporary back', 'Slim dark legs'] },
      { id: 'cortland-three', name: 'Cortland Leather Three-Seater', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop3/tri/02a.jpg', 'assets/shop3/tri/02b.jpg'], desc: 'Cognac leather with plush stacked back cushions and a side bolster — a relaxed, generous three-seater with a built-in power control.', feats: ['Cognac leather', 'Stacked back cushions', 'Power headrest control', 'Three-seat length'] },
      { id: 'noir-three', name: 'Noir Leather Three-Seater', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop3/tri/03a.jpg', 'assets/shop3/tri/03b.jpg'], desc: 'A low, tailored black leather three-seater with loose back bolsters on slim metal legs — quietly architectural.', feats: ['Black leather', 'Loose back bolsters', 'Slim metal legs', 'Low tailored frame'] },
      { id: 'sabbia-chaise-sectional', name: 'Sabbia Cream Chaise Sectional', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop3/tri/04a.jpg', 'assets/shop3/tri/04b.jpg'], desc: 'A cream leather sectional with a grid-tufted chaise return, sunlit and soft — a bright, family-scale landing spot.', feats: ['Cream leather', 'Grid-tufted chaise', 'Adjustable headrests', 'Seats four+'] },
      { id: 'walnut-three-recliner', name: 'Walnut Leather Recliner Sofa', cat: 'living', sub: 'Recliner Sofas', imgs: ['assets/shop3/tri/05a.jpg', 'assets/shop3/tri/05b.jpg'], desc: 'A brown leather three-seater with flip-up headrests, pillow arms and full recline on sculptural chrome feet.', feats: ['Brown leather', 'Flip-up headrests', 'Three reclining seats', 'Chrome sled feet'] },
      { id: 'cortina-two-2', name: 'Cortina Leather Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop3/two/01a.jpg', 'assets/shop3/two/01b.jpg'], desc: 'A compact cognac leather loveseat with rolled cushion backs and rounded arms — warm and easygoing for smaller rooms.', feats: ['Cognac leather', 'Rolled cushion backs', 'Rounded arms', 'Two-seat scale'] },
      { id: 'marine-two-2', name: 'Marine Leather Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop3/two/02a.jpg', 'assets/shop3/two/02b.jpg'], desc: 'Deep navy leather with pillowy loose cushions on polished metal legs — a crisp, cool-toned loveseat.', feats: ['Deep navy leather', 'Loose pillow cushions', 'Polished metal legs', 'Two-seat footprint'] },
      { id: 'dune-two', name: 'Dune Leather Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop3/two/03a.jpg', 'assets/shop3/two/03b.jpg'], desc: 'A sand-tan leather two-seater with lifted headrests and a soft tufted seat — quiet, warm and endlessly comfortable.', feats: ['Sand-tan leather', 'Adjustable headrests', 'Tufted seat', 'Slim black legs'] },
      { id: 'olive-curved-two', name: 'Olive Curved Leather Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop3/two/04a.jpg', 'assets/shop3/two/04b.jpg', 'assets/shop3/two/04c.jpg'], desc: 'A gently curved olive leather loveseat with pillowy bolster arms and matching cushions — sculptural and soft on a wood plinth.', feats: ['Olive-green leather', 'Curved silhouette', 'Pillow bolster arms', 'Wood plinth base'] },
      { id: 'noir-split-marble-table', name: 'Noir Split Marble Table', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop3/tb/01a.jpg', 'assets/shop3/tb/01b.jpg'], desc: 'A sculptural black marble slab with an offset white-marble tier on polished steel legs — graphic, low and glamorous.', feats: ['Black + white marble', 'Offset two-tier top', 'Polished steel legs', 'Sculptural slab form'] },
      { id: 'noir-drum-tray-pair', name: 'Noir Drum Tray Tables', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop3/tb/02a.jpg', 'assets/shop3/tb/02b.jpg'], desc: 'A pair of matte-black round tray tables on marble-footed drum bases — nesting companions in two heights.', feats: ['Matte black trays', 'Marble-footed drums', 'Nesting pair', 'Two heights'] },
      { id: 'travertine-oval-wood', name: 'Travertine Oval & Wood Table', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop3/tb/03a.jpg', 'assets/shop3/tb/03b.jpg'], desc: 'A broad travertine oval on brass cylinder legs paired with a dark-oak oval — warm stone meets timber in a layered duo.', feats: ['Travertine oval top', 'Brass cylinder legs', 'Dark-oak companion', 'Layered pairing'] },
      { id: 'cirrus-grey-nest', name: 'Cirrus Grey Marble Nesting Pair', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop3/tb/04a.jpg', 'assets/shop3/tb/04b.jpg'], desc: 'Two grey-veined marble ovals on sculpted brass bases, sliding together into one flowing stone surface.', feats: ['Grey-veined marble', 'Sculpted brass bases', 'Nesting ovals', 'High-polish finish'] },
      { id: 'noir-crystal-cart', name: 'Noir Crystal Bar Cart', cat: 'tables', sub: 'Bar Carts', imgs: ['assets/shop3/tb/05a.jpg'], desc: 'A two-tier black leather-wrapped trolley with gold-stitched trays and brass rails — rolling service dressed for the evening.', feats: ['Two-tier trays', 'Leather-wrapped frame', 'Brass rails & castors', 'Gold contrast stitch'] },
      { id: 'terra-round-duo', name: 'Terra Round Marble Duo', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop3/tb/06a.jpg', 'assets/shop3/tb/06b.jpg'], desc: 'A travertine oval paired with a dark red-veined marble round on a brushed steel base — a warm, contrasting two-piece.', feats: ['Travertine + dark marble', 'Brushed steel base', 'Round + oval pair', 'Contrasting tones'] },
      { id: 'esmeralda-round-pair', name: 'Esmeralda Marble Round Pair', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop3/tb/07a.jpg', 'assets/shop3/tb/07b.jpg'], desc: 'A white marble round beside a deep-green marble round on gleaming gold drum bases — a jewel-like nesting duo.', feats: ['White + green marble', 'Gold drum bases', 'Nesting round pair', 'Two heights'] },
      { id: 'luna-c-side-table', name: 'Luna Sculptural Side Table', cat: 'tables', sub: 'Side Tables', imgs: ['assets/shop3/tb/08a.jpg'], desc: 'A C-shaped side table in brushed steel with a swept-in white-marble foot — slides over a sofa arm or beside a lounge chair.', feats: ['C-shaped cantilever', 'Brushed steel body', 'White-marble foot', 'Sofa-side scale'] },
      { id: 'piano-split-table', name: 'Piano Split-Level Table', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop3/tb/09a.jpg', 'assets/shop3/tb/09b.jpg'], desc: 'Two offset rectangular tops — dark oak and pale travertine — on brushed plinth bases, sliding apart into a split-level surface.', feats: ['Dark oak + travertine', 'Offset split levels', 'Brushed plinth bases', 'Rectangular form'] },
      { id: 'mandala-relief', name: 'Rope Mandala Relief', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop3/ar/01a.jpg'], desc: 'A large two-panel relief of coiled natural rope radiating from a gilded core — dimensional, tactile and warm as a sun.', feats: ['Coiled-rope relief', 'Two-panel diptych', 'Gilded centre core', 'Natural fibre texture'] },
      { id: 'lunar-branch-relief', name: 'Lunar Branch Relief', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop3/ar/02a.jpg'], desc: 'A backlit crescent moon in textured plaster with a sculptural branch crossing its face — a quiet, glowing focal piece.', feats: ['Backlit crescent form', 'Textured plaster ground', 'Sculptural branch', 'Framed portrait format'] },
      { id: 'midas-gold-canvas', name: 'Midas Gold-Leaf Canvas', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop3/ar/03a.jpg'], desc: 'A dramatic canvas where molten gold leaf rises out of a black textured ground — pure glamour, framed in slim black.', feats: ['Gold-leaf on black', 'Heavy impasto texture', 'Portrait format', 'Slim black frame'] },
      { id: 'bouquet-relief', name: 'Golden Bouquet Relief', cat: 'art', sub: 'Wall Art', imgs: ['assets/shop3/ar/04a.jpg'], desc: 'A sculpted vase spilling a burst of gilded three-dimensional blooms across a cream textured canvas — floral relief with real depth.', feats: ['3D floral relief', 'Sculpted plaster vase', 'Gold-leaf blossoms', 'Cream textured ground'] },
      { id: 'cubo-pendant-cluster', name: 'Cubo Glass Cube Cluster', cat: 'lighting', sub: 'Pendants', imgs: ['assets/shop3/lt/01a.jpg', 'assets/shop3/lt/01b.jpg', 'assets/shop3/lt/01c.jpg'], desc: 'A cascading cluster of textured glass cubes in polished gold, staggered on a mirrored ceiling disc — a jewel-box of light.', feats: ['Textured glass cubes', 'Polished gold caps', 'Mirrored ceiling disc', 'Staggered cascade'] },
      { id: 'lumina-linear-bar', name: 'Lumina Alabaster Linear Light', cat: 'lighting', sub: 'Linear', imgs: ['assets/shop3/lt/02a.jpg', 'assets/shop3/lt/02b.jpg', 'assets/shop3/lt/02c.jpg'], desc: 'Twin glowing alabaster tubes threaded with marble discs and cube drops — a dramatic double-bar suspension for a long table.', feats: ['Twin alabaster tubes', 'Marble disc + cube drops', 'Warm even glow', 'Table-length suspension'] },
      { id: 'aurora-globe-pendant', name: 'Aurora Ribbed Globe Pendant', cat: 'lighting', sub: 'Pendants', imgs: ['assets/shop3/lt/03a.jpg', 'assets/shop3/lt/03b.jpg'], desc: 'A ribbed clear-glass globe below a slim amber cylinder on a brass stem — a warm, sculptural single pendant.', feats: ['Ribbed glass globe', 'Amber glass cylinder', 'Brass stem & cap', 'Warm filament glow'] },
      { id: 'petalo-linear-chandelier', name: 'Petalo Brass Linear Chandelier', cat: 'lighting', sub: 'Linear', imgs: ['assets/shop3/lt/04a.jpg', 'assets/shop3/lt/04b.jpg', 'assets/shop3/lt/04c.jpg'], desc: 'A long brass fixture bristling with gilded petal discs on a fine-rod grid, lit from within — sculpture for above the table.', feats: ['Gilded petal discs', 'Fine brass-rod grid', 'Integrated warm light', 'Linear centrepiece'] },
      { id: 'orbita-globe-cluster', name: 'Orbita Glass Globe Cluster', cat: 'lighting', sub: 'Pendants', imgs: ['assets/shop3/lt/05a.jpg', 'assets/shop3/lt/05b.jpg'], desc: 'Clear glass globes with softly glowing inner bulbs suspended around a gilded ring — a constellation for the stairwell or void.', feats: ['Clear glass globes', 'Gilded suspension ring', 'Staggered heights', 'Warm inner glow'] },
      { id: 'tubo-linear-light', name: 'Tubo Glass Disc Linear Light', cat: 'lighting', sub: 'Linear', imgs: ['assets/shop3/lt/06a.jpg', 'assets/shop3/lt/06b.jpg'], desc: 'Frosted glass tubes threaded through oversized clear glass discs on brass fittings — two floating bars of warm light.', feats: ['Frosted glass tubes', 'Oversized clear discs', 'Brass fittings', 'Twin-bar suspension'] },
      { id: 'sfera-mesh-cluster', name: 'Sfera Mesh Sphere Cluster', cat: 'lighting', sub: 'Pendants', imgs: ['assets/shop3/lt/07a.jpg', 'assets/shop3/lt/07b.jpg'], desc: 'A cascade of half-open spheres — matte black domes over gilded wire mesh — glowing warm from within on black cords.', feats: ['Black dome + mesh spheres', 'Warm internal glow', 'Staggered cascade', 'Black cord suspension'] },
      { id: 'bell-glass-trio', name: 'Bell Glass Triple Pendant', cat: 'lighting', sub: 'Pendants', imgs: ['assets/shop3/lt/08a.jpg'], desc: 'Three clear glass globes, each capped in brass and holding a fluted inner shade with a glowing halo ring — a warm staggered trio.', feats: ['Clear glass globes', 'Brass caps', 'Fluted inner shades', 'Glowing halo rings'] },

      // ---- Added by showroom asset audit: armchairs ----
      { id: 'luna-rotunda-lounge', name: 'Luna Rotunda Lounge', cat: 'armchairs', sub: 'Swivel Chairs', imgs: ['assets/shop/arm/07.jpg', 'assets/shop/arm/11.jpg'], desc: 'A great curve of camel leather wrapped into an oversized round lounge — part chair, part daybed, entirely indulgent.', feats: ['Oversized round form', 'Camel full-grain leather', 'Wraparound curved back', 'Generous lounge scale'] },
      { id: 'sella-swivel-lounge', name: 'Sella Leather Swivel Lounge', cat: 'armchairs', sub: 'Swivel Chairs', imgs: ['assets/shop/arm/10.jpg'], desc: 'Saddle-brown leather draped over a deep, winged seat on a black disc base — a gallery chair that reads as sculpture from every angle.', feats: ['Saddle-brown leather', 'Deep winged seat', 'Black disc swivel base', 'Sculptural profile'] },
      { id: 'vela-sling-chair', name: 'Vela Sculpted Sling Chair', cat: 'armchairs', sub: 'Accent Chairs', imgs: ['assets/shop/arm/12.jpg'], desc: 'A pale leather sling suspended in a sweeping bentwood frame, finished with a striped bolster — light, graphic and quietly architectural.', feats: ['Sculpted bentwood frame', 'Pale leather sling seat', 'Striped accent bolster', 'Statement corner piece'] },
      { id: 'buttercream-wing-chair', name: 'Buttercream Wing Chair', cat: 'armchairs', sub: 'Accent Chairs', imgs: ['assets/shop/arm/13.jpg'], desc: 'Butter-soft cream leather gathered into a winged shell with a tucked seat — a bright, tailored perch for the reading corner.', feats: ['Butter-cream leather', 'Winged shell back', 'Tailored tucked seat', 'Compact accent scale'] },
      { id: 'sorrel-highback-lounge', name: 'Sorrel High-Back Lounge', cat: 'armchairs', sub: 'Accent Chairs', imgs: ['assets/shop/arm/15.jpg'], desc: 'Tan leather pulled tall over a high, supportive back on slim metal legs — upright comfort with a long, elegant line.', feats: ['Tan top-grain leather', 'High supportive back', 'Slim metal legs', 'Upright lounge posture'] },

      // ---- Added by showroom asset audit: pairs ----
      { id: 'apricot-curve-pair', name: 'Apricot Curve Lounge Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/shop/arm/05.jpg'], desc: 'A matched pair of armless apricot leather curves beside a travertine hourglass table — soft geometry in the warmest shade of the evening.', feats: ['Sold as a set of two', 'Apricot-tan leather', 'Armless curved shells', 'Slim metal feet'] },
      { id: 'pearl-recliner-pair', name: 'Pearl Tufted Recliner Pair', cat: 'pairs', sub: 'Pair of Chairs', imgs: ['assets/products/4691.jpg', 'assets/products/4692.jpg'], desc: 'Two high-backed recliners in pearl leather with biscuit-tufted backs, padded headrest cushions and one-touch power recline on polished star bases — a matched pair for the reading corner.', feats: ['Sold as a set of two', 'Pearl full-grain leather', 'Biscuit-tufted high backs', 'One-touch power recline'] },

      // ---- Added by showroom asset audit: single sitters ----
      { id: 'talpa-barrel-swivel', name: 'Talpa Barrel Swivel Chair', cat: 'living', sub: 'Single Sitter', imgs: ['assets/shop/single/06.jpg', 'assets/shop/single/07.jpg', 'assets/shop/single/08.jpg'], desc: 'A smooth taupe leather barrel on a slim star base — quiet curves, a deep seat and a turn as smooth as the hide it wears.', feats: ['Taupe full-grain leather', 'Barrel-back silhouette', 'Deep cushioned seat', 'Star swivel base'] },
      { id: 'avorio-recliner-ottoman', name: 'Avorio Recliner & Ottoman', cat: 'living', sub: 'Single Sitter', imgs: ['assets/shop/single/09.jpg', 'assets/shop/single/10.jpg', 'assets/shop/single/11.jpg'], desc: 'A cream leather recliner with its matching ottoman on polished star feet — angular outside, endlessly forgiving inside.', feats: ['Cream full-grain leather', 'Matching ottoman included', 'Reclining back', 'Polished star feet'] },

      // ---- Added by showroom asset audit: two sitters ----
      { id: 'salvia-two', name: 'Salvia Leather Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop/two/01.jpg', 'assets/shop/two/02.jpg', 'assets/shop/two/03.jpg'], desc: 'Sage-green leather with lifted headrests and a calm, tailored line — two seats of quiet colour for the modern apartment.', feats: ['Sage-green leather', 'Adjustable headrests', 'Tailored stitching', 'Compact two-seat scale'] },
      { id: 'grafite-two', name: 'Grafite Leather Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop/two/04.jpg', 'assets/shop/two/05.jpg'], desc: 'Graphite leather, clean lines and softly flared arms — a compact two-seater that dresses a small room in charcoal.', feats: ['Graphite full-grain leather', 'Softly flared arms', 'Loose back cushions', 'Compact footprint'] },
      { id: 'marigold-two', name: 'Marigold Leather Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop/two/06.jpg', 'assets/shop/two/07.jpg'], desc: 'Marigold done right — saturated golden leather with winged arms and patterned teal pillows, a two-seater that brings its own sunshine.', feats: ['Marigold-gold leather', 'Winged flared arms', 'Teal accent pillows', 'Statement colour piece'] },
      { id: 'nuvola-curved-loveseat', name: 'Nuvola Curved Loveseat', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop/two2/03.jpg'], desc: 'An asymmetric cream curve with one high wrapping arm and rust bolsters — a loveseat drawn in a single, confident stroke.', feats: ['Asymmetric curved shell', 'Cream textured weave', 'Rust accent bolsters', 'Sculptural silhouette'] },
      { id: 'biscotto-compact-loveseat', name: 'Biscotto Compact Loveseat', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop/two2/05.jpg'], desc: 'A crisp, track-armed loveseat in biscuit leather — upright, compact and endlessly useful in smaller rooms.', feats: ['Biscuit-tan leather', 'Clean track arms', 'Upright supportive sit', 'Small-room footprint'] },
      { id: 'tortora-highback-two', name: 'Tortora High-Back Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop/two2/07.jpg', 'assets/shop/two2/08.jpg'], desc: 'Dove-taupe leather with tall, sheltering backs and block arms — a two-seater built for long evenings of good posture and better conversation.', feats: ['Dove-taupe leather', 'Tall sheltering backs', 'Block arms', 'Firm supportive seats'] },
      { id: 'pietra-headrest-two', name: 'Pietra Headrest Two-Seater', cat: 'living', sub: 'Two Sitter', imgs: ['assets/shop/two2/09.jpg', 'assets/shop/two2/10.jpg'], desc: 'Stone-grey leather riding on polished runners, with headrests that lift at a touch — engineering dressed in a very good suit.', feats: ['Stone-grey leather', 'Adjustable headrests', 'Polished runner base', 'Tailored seams'] },

      // ---- Added by showroom asset audit: triple sitters & recliner sofas ----
      { id: 'tartufo-chaise-sectional', name: 'Tartufo Chaise Sectional', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop/three/02.jpg', 'assets/shop/three/03.jpg', 'assets/shop/three/01.jpg'], desc: 'Mushroom-taupe leather stretching into a long chaise return, with lifted headrests along its whole run — the sectional our showroom is arranged around.', feats: ['Mushroom-taupe leather', 'Chaise return end', 'Adjustable headrests', 'Seats four+'] },
      { id: 'salice-recliner-sofa', name: 'Salice Power Recliner Sofa', cat: 'living', sub: 'Recliner Sofas', imgs: ['assets/shop/three/04.jpg', 'assets/shop/three/05.jpg'], desc: 'A sage-green three-seater with one-touch power recline and patterned silk bolsters — soft colour, softer mechanics.', feats: ['Sage-green leather', 'One-touch power recline', 'Patterned silk bolsters', 'Three-seat length'] },
      { id: 'grafite-tre', name: 'Grafite Leather Three-Seater', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop/three/06.jpg', 'assets/shop/three/08.jpg', 'assets/shop/three/09.jpg'], desc: 'Charcoal leather with cream cushions and gently swept arms — a graphite three-seater that anchors a room without darkening it.', feats: ['Charcoal full-grain leather', 'Cream accent cushions', 'Gently swept arms', 'Slim dark legs'] },
      { id: 'marigold-grand-sofa', name: 'Marigold Grand Sofa', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop/three/10.jpg', 'assets/shop/three/14.jpg'], desc: 'The Marigold at full length — saturated golden leather, winged arms and navy pillows across three wide seats.', feats: ['Marigold-gold leather', 'Winged flared arms', 'Navy accent pillows', 'Three-seat length'] },
      { id: 'miele-pillowtop-sofa', name: 'Miele Pillow-Top Sofa', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop/three/11.jpg', 'assets/shop/three/12.jpg', 'assets/shop/three/13.jpg'], desc: 'Honey-caramel leather crowned with high pillow-top backs — a three-seater that pours like its namesake.', feats: ['Honey-caramel leather', 'High pillow-top backs', 'Plump padded arms', 'Three-seat comfort'] },
      { id: 'arco-curved-sectional', name: 'Arco Curved Sectional', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop/three2/01.jpg', 'assets/shop/three2/02.jpg', 'assets/shop/three2/03.jpg'], desc: 'Cognac leather bent through a long, architectural corner on slim dark legs — an arc of a sofa that turns the room with it.', feats: ['Cognac full-grain leather', 'Curved corner form', 'Slim dark legs', 'Seats five'] },
      { id: 'crema-boucle-chaise', name: 'Crema Bouclé Chaise', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop/three2/04.jpg'], desc: 'A cream bouclé curve with an open chaise and companion ottoman — sculptural softness for a sunlit corner.', feats: ['Cream bouclé weave', 'Open chaise end', 'Companion ottoman', 'Organic curved form'] },
      { id: 'trama-chenille-sectional', name: 'Trama Chenille Sectional', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop/three2/05.jpg', 'assets/shop/three2/06.jpg'], desc: 'Pale patterned chenille heaped with pillows along a deep corner run — texture on texture, softness on softness.', feats: ['Patterned pale chenille', 'Deep corner configuration', 'Layered back pillows', 'Family-scale seating'] },
      { id: 'storia-flared-sofa', name: 'Storia Flared-Arm Sofa', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop/three2/07.jpg'], desc: 'Caramel leather with dramatic flared arms, photographed beneath the aprilstory techniques wall it was built by.', feats: ['Caramel full-grain leather', 'Dramatic flared arms', 'Low lounge profile', 'aprilstory engineering'] },
      { id: 'cammello-highback-sofa', name: 'Cammello High-Back Sofa', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop/three2/08.jpg'], desc: 'Camel leather with tall, enveloping backs and softly rounded arms — a three-seater that sits you upright and keeps you there happily.', feats: ['Camel full-grain leather', 'Tall enveloping backs', 'Rounded arms', 'Firm supportive sit'] },
      { id: 'uliveto-chaise-sectional', name: 'Uliveto Chaise Sectional', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop/three2/09.jpg', 'assets/shop/three2/10.jpg'], desc: 'Olive-sage leather in a long modular run with an open chaise and ottoman — earthy, low and endlessly rearrangeable.', feats: ['Olive-sage leather', 'Modular configuration', 'Open chaise + ottoman', 'Low contemporary back'] },
      { id: 'cenere-two-tone-sofa', name: 'Cenere Two-Tone Sofa', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop/three2/11.jpg', 'assets/shop/three2/12.jpg'], desc: 'Pearl and ash leather worked into one quiet gradient across three seats — dressed here with a chenille throw it never really needs.', feats: ['Two-tone pearl & ash', 'Contrast piped seams', 'Plump back cushions', 'Three-seat length'] },
      { id: 'dorato-two-tone-sofa', name: 'Dorato Two-Tone Sofa', cat: 'living', sub: 'Triple Sitter', imgs: ['assets/shop/three2/13.jpg'], desc: 'Butter and caramel leather split across a wide, low frame — a two-tone three-seater that glows in afternoon light.', feats: ['Butter & caramel leather', 'Wide low frame', 'Two-tone tailoring', 'Seats three+'] },

      // ---- Added by showroom asset audit: sofa sets ----
      { id: 'salvia-verde-set', name: 'Salvia Verde Sofa Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop/set/01.jpg', 'assets/shop/set/02.jpg'], desc: 'Sage-green leather sofas squared around cognac swivel chairs and a black-marble table — the aprilstory floor set that opens our showroom.', feats: ['Sage-green leather sofas', 'Cognac swivel chairs', 'Complete living floor', 'aprilstory flagship set'] },
      { id: 'carbone-recliner-set', name: 'Carbone Recliner Sofa Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop/set/03.jpg', 'assets/shop/set/04.jpg'], desc: 'Charcoal leather sofas with power recline at every seat, gathered around a dark drum table — a set for cinema evenings that look this good with the lights on.', feats: ['Charcoal full-grain leather', 'Power recline throughout', 'Sofa + recliner chairs', 'Dark drum centre table'] },
      { id: 'avena-chenille-set', name: 'Avena Chenille Living Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop/set/05.jpg', 'assets/shop/set/06.jpg', 'assets/shop/set/07.jpg', 'assets/shop/set/08.jpg'], desc: 'Oat chenille sofas with plump bolster arms, warmed by caramel leather lounge chairs and stone ovals — the complete, sink-in family floor.', feats: ['Oat patterned chenille', 'Plump bolster arms', 'Caramel leather chairs', 'Complete living set'] },
      { id: 'duna-grande-set', name: 'Duna Grande Chenille Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop/set/09.jpg'], desc: 'A grand U of flecked sand chenille around a white marble slab — one uninterrupted horizon of softness for the whole household.', feats: ['Flecked sand chenille', 'Grand U configuration', 'White marble table', 'Seats seven+'] },
      { id: 'marigold-lounge-set', name: 'Marigold Lounge Set', cat: 'living', sub: 'Sofa Sets', imgs: ['assets/shop/set/10.jpg', 'assets/shop/set/11.jpg', 'assets/shop/set/12.jpg'], desc: 'Marigold leather sofas ringed by taupe swivel loungers and white marble tables — the boldest floor in the house, balanced to the last cushion.', feats: ['Marigold-gold leather', 'Taupe swivel loungers', 'White marble tables', 'Statement colour set'] },

      // ---- Added by showroom asset audit: tables ----
      { id: 'perla-noir-duo', name: 'Perla Noir Nesting Duo', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop/tables/01.jpg', 'assets/shop/tables/02.jpg'], desc: 'A white pebble of marble sliding beneath a black-veined companion on a cream plinth — marble that anchors a room, hand-selected slab by slab.', feats: ['White + black marble', 'Pebble-form tops', 'Cream plinth base', 'Nesting duo'] },
      { id: 'quadra-marble-duo', name: 'Quadra Marble Duo', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop/tables/03.jpg', 'assets/shop/tables/04.jpg'], desc: 'A broad white-marble square on a chrome V-base with a black marble triangle at its side — sharp geometry in soft stone.', feats: ['White marble square', 'Black marble companion', 'Chrome V-bases', 'Graphic pairing'] },
      { id: 'ovale-duo-tables', name: 'Ovale Duo Tables', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop/tables/05.jpg', 'assets/shop/tables/06.jpg'], desc: 'A white marble oval on a curved foot beside a dark stone drum — a quiet two-piece that layers height without noise.', feats: ['White marble oval', 'Dark stone drum', 'Two-height layering', 'Soft neutral palette'] },
      { id: 'trio-notte-nest', name: 'Trio Notte Nesting Tables', cat: 'tables', sub: 'Coffee Tables', imgs: ['assets/shop/tables/07.jpg'], desc: 'Three dark rounds — marble, textured glass and stone — nesting on slim black legs, ready to scatter when the guests arrive.', feats: ['Set of three rounds', 'Marble, glass & stone', 'Slim black legs', 'Scatter-and-nest design'] },
    ];
  }

  _craftSlides() {
    const N = 'assets/new/';
    return [
      { img: 'assets/catalog/craft/1.jpg', title: 'six exclusive techniques', caption: 'The techniques wall', text: 'Every LuxLiving × aprilstory piece is built on six engineered techniques — frame, adhesive, structure, cover, springs and foam. Our showroom wall walks you through each one.' },
      { img: 'assets/catalog/craft/2.jpg', title: 'materials, in your hands', caption: 'Live material stations', text: 'Five live stations sit under the wall, each demonstrating one technique with the actual materials — so you can see, touch and test what goes inside your sofa.' },
      { img: 'assets/catalog/craft/3.jpg', title: 'imported leather care', caption: 'Leather care station', text: 'Top-grain leather from responsibly raised cattle, dyed through a 96-hour drum process. Every sofa set ships with an original imported Italian maintenance kit.' },
      { img: 'assets/catalog/craft/4.jpg', title: 'water-based adhesive', caption: 'Adhesive comparison rig', text: 'All products use eco-friendly water-based adhesive — zero formaldehyde, odorless, heat-resistant and non-corrosive, with almost no TVOC. See it side-by-side against solvent glue.' },
      { img: 'assets/catalog/craft/5.jpg', title: 'genuine cowhide', caption: 'Color-fastness test', text: 'An average of 6–10 pieces of cowhide creates one leather sofa. Each hide is dry-rub tested 500 times and wet-rub tested 250 times — no peeling, no fading.' },
      { img: 'assets/catalog/craft/6.jpg', title: '50,000-cycle fold test', caption: 'Bending durability rig', text: 'Before any leather earns a place on a frame, it passes 50,000 bending cycles on this rig without cracking — firm, resistant to folding, durable and ever new.' },
      { img: 'assets/catalog/craft/7.jpg', title: 'foam & snake springs', caption: 'Foam & spring station', text: 'High-density 32 kg/m³ foam meets carbon-steel snake springs (0.82% carbon) tested through 60,000 compressions — each pair supporting up to 150 pounds.' },
    ];
  }

  _wallSlides() {
    return [
      { img: 'assets/catalog/craft/wall-1.jpg', num: '01·02', title: 'frame & environmental care', caption: 'On the wall · Frame · Adhesive', text: 'Super-sturdy support starts with carefully selected imported larch, denser than 600 kg/m³. It is bonded with an eco-friendly, water-based adhesive — free of benzene, halogenated hydrocarbons and other harmful substances. Strong bones, healthy and green.' },
      { img: 'assets/catalog/craft/wall-2.jpg', num: '03·04', title: 'structure & cover', caption: 'On the wall · Structure · Cover', text: 'The seat structure conforms to human ergonomics, giving comprehensive, scientific lumbar support. Its cover’s colour-fastness far exceeds national standards — passing over 50,000 fold tests without cracking, so it stays durable and ever-new.' },
      { img: 'assets/catalog/craft/wall-3.jpg', num: '05·06', title: 'springs & foam', caption: 'On the wall · Springs · Foam', text: 'Imported carbon-steel snake springs at 0.82% carbon are tested through tens of thousands of compression cycles for super-strong resilience. Above them sits high-resilience foam denser than 25 kg/m³ — soft, supportive and collapse-resistant.' },
      { img: 'assets/catalog/craft/wall-4.jpg', num: '—', title: 'the aprilstory house', caption: 'Our flagship partner', text: 'Every technique on this wall belongs to aprilstory — the leaf-and-bird furniture house whose engineered, 100% leather seating our showroom is built around. Lux Living is its authorised India partner.' },
    ];
  }

  _instaData() {
    const U = 'https://www.instagram.com/lux.living34/';
    return [
      { img: 'assets/shop/single/01.jpg', likes: '842', comments: '37', time: '2 days ago', url: U, caption: 'The Aria swivel lounge chair in tan leather — the piece everyone photographs first. Now on our showroom floor.', tags: ['#luxliving', '#leatherchair', '#aprilstory'] },
      { img: 'assets/shop/two/06.jpg', likes: '1.2k', comments: '54', time: '5 days ago', url: U, caption: 'Marigold done right. This two-seater brings warmth to any living room. Swing by the store to feel the grain.', tags: ['#statementsofa', '#interiordesign', '#panipat'] },
      { img: 'assets/shop/bedroom/01.jpg', likes: '967', comments: '41', time: '1 week ago', url: U, caption: 'Rest, reimagined. The Cocoon leather bed with its curved headboard and integrated bench.', tags: ['#bedroomdesign', '#leatherbed', '#luxliving'] },
      { img: 'assets/shop/set/01.jpg', likes: '2.1k', comments: '88', time: '1 week ago', url: U, caption: 'Modular seating meets black-marble nesting tables. Configure it your way — take the full set or piece by piece.', tags: ['#modularsofa', '#marbletable', '#homefeeling'] },
      { img: 'assets/shop/two/04.jpg', likes: '731', comments: '29', time: '2 weeks ago', url: U, caption: 'Graphite leather, clean lines. A compact two-seater for the modern apartment.', tags: ['#compactliving', '#leathersofa', '#aresitalia'] },
      { img: 'assets/shop/tables/01.jpg', likes: '1.5k', comments: '62', time: '3 weeks ago', url: U, caption: 'Marble that anchors a room. Our coffee & side table pairing, hand-selected slabs.', tags: ['#marble', '#coffeetable', '#luxurydecor'] },
    ];
  }

  _brands() {
    return [
      {
        id: 'aprilstory',
        name: 'aprilstory',
        origin: 'China',
        material: '100% Leather',
        kicker: 'Flagship Leather House',
        img: 'assets/shop/set/01.jpg',
        pos: 'center',
        blurb: 'One of China\'s top furniture houses. aprilstory pairs a signature leaf-and-bird identity with rigorously engineered, 100% genuine-leather seating — the pieces our craft tour is built around.',
        tags: ['100% Leather', 'Franchise Partner', 'Since 2009'],
        tagline: 'engineered comfort, chinese design heritage',
        material2: '100% Genuine Leather',
        paras: [
          'aprilstory is one of the leading furniture brands in China, known for leather seating built on six exclusive techniques — from imported larch frames to 50,000-cycle fold-tested hides.',
          'As their authorised India franchise partner, Lux Living brings the full aprilstory catalogue across four branches — with the flagship showroom in Panipat, Haryana.',
          'Every aprilstory sofa ships with an original imported leather-maintenance kit, so the piece stays firm, supple and ever-new for years.',
        ],
        facts: [
          { label: 'Origin', value: 'China' },
          { label: 'Material', value: '100% Leather' },
          { label: 'Partnership', value: 'Authorised Franchise' },
          { label: 'Branches', value: '4 in India' },
        ],
        locLabel: 'Where to Find It',
        locTitle: 'four branches across india',
        locations: ['Hyderabad', 'Mumbai', 'Kolkata', 'Panipat, Haryana · Flagship'],
      },
      {
        id: 'ares-italia',
        name: 'Ares Italia',
        origin: 'Italy',
        material: 'Leather & Fabric',
        kicker: 'Italian Design Atelier',
        img: 'assets/shop/three/01.jpg',
        pos: 'center',
        blurb: 'Designed in Italy, crafted in Hong Kong. Ares Italia brings continental proportion and tailoring to both leather and fabric upholstery, delivered to our Panipat flagship.',
        tags: ['Designed in Italy', 'Leather & Fabric', 'Franchise Partner'],
        tagline: 'designed in italy, tailored for living',
        paras: [
          'Ares Italia is an Italian furniture house — every silhouette is designed in Italy, then precision-manufactured in Hong Kong, China.',
          'The range spans both 100% leather and premium fabric upholstery, giving you Italian design language in the texture of your choice.',
          'Lux Living carries Ares Italia as a franchise partner, with delivery to our Panipat, Haryana location.',
        ],
        facts: [
          { label: 'Designed In', value: 'Italy' },
          { label: 'Manufactured', value: 'Hong Kong' },
          { label: 'Material', value: 'Leather & Fabric' },
          { label: 'Delivered To', value: 'Panipat, Haryana' },
        ],
        locLabel: 'Availability',
        locTitle: 'delivered to panipat, haryana',
        locations: ['Panipat, Haryana', 'By Consultation'],
      },
      {
        id: 'home-feeling',
        name: 'Home Feeling',
        origin: 'Fabric House',
        material: 'Premium Fabric',
        kicker: 'Fabric Specialist',
        img: 'assets/shop/set/06.jpg',
        pos: 'center',
        blurb: 'Our dedicated fabric brand — soft, contemporary upholstery for family living, offered alongside Ares Italia\'s fabric line as a franchise partner.',
        tags: ['Premium Fabric', 'Everyday Living', 'Franchise Partner'],
        tagline: 'soft comfort for everyday living',
        paras: [
          'Home Feeling is our premium fabric furniture brand, focused on relaxed, contemporary upholstery made for real family living.',
          'Together with the Ares Italia fabric line, it rounds out our fabric offering — a softer counterpart to the 100% leather aprilstory range.',
          'Lux Living offers Home Feeling as a franchise partner, with pieces available to view and order through our showroom.',
        ],
        facts: [
          { label: 'Category', value: 'Fabric' },
          { label: 'Material', value: 'Premium Fabric' },
          { label: 'Partnership', value: 'Authorised Franchise' },
          { label: 'Best For', value: 'Family Living' },
        ],
        locLabel: 'Availability',
        locTitle: 'at our showroom',
        locations: ['Panipat, Haryana', 'By Consultation'],
      },
    ];
  }

  _techniques() {
    return [
      { num: '01', tag: 'Frame', title: 'super sturdy support', desc: 'Carefully selected imported larch as the main frame material, with a density higher than 600 kg/m³.' },
      { num: '02', tag: 'Adhesive', title: 'healthy and green', desc: 'Eco-friendly water-based adhesive — free of benzene, halogenated hydrocarbons and other harmful substances.' },
      { num: '03', tag: 'Structure', title: 'fit for the body', desc: 'Ergonomic geometry conforming to human proportions, with comprehensive scientific lumbar support.' },
      { num: '04', tag: 'Cover', title: 'durable, ever new', desc: 'Color fastness far exceeds national standards — passed over 50,000 fold tests without cracking.' },
      { num: '05', tag: 'Springs', title: 'strong resilience', desc: 'Imported carbon-steel snake springs with 0.82% carbon content, tested for 60,000 compression cycles.' },
      { num: '06', tag: 'Foam', title: 'collapse resistant', desc: 'Carefully selected high-resilience foam with a density above 32 kg/m³ — soft, supportive and shape-retaining.' },
    ];
  }

  _testimonials() {
    return [
      { text: '"LuxLiving transformed our entire home. The quality is unmatched — we receive compliments from every guest."', author: 'Rajesh Sharma', loc: 'Panipat, Haryana', initials: 'RS' },
      { text: '"The design consultation was incredible. They curated pieces that fit our home beautifully. The chandelier is a showstopper!"', author: 'Priya Aggarwal', loc: 'Delhi NCR', initials: 'PA' },
      { text: '"From the moment we walked in, we knew this was different. The craftsmanship and designs — 5 stars isn\'t enough!"', author: 'Vikram Gupta', loc: 'Karnal, Haryana', initials: 'VG' },
      { text: '"We furnished our entire villa with LuxLiving. The bedroom collection is absolutely dreamy. Outstanding!"', author: 'Neha Kapoor', loc: 'Chandigarh', initials: 'NK' },
    ];
  }
}
window.LUX = new LuxData();
